tarantool/http

http/server.lua
Added `return self` to the `set_hook()` function.
=> Fixed set_hook() in the server.lua

README.md, http/server.lua
`handler` and `before_routes` hooks were broken. This pull request make them work again. See commit messages for more details.
=> Fix handler and before_routes hooks

http/server.lua
Fix bug in uri_escape and uri_unescape when multiple arguments with same name caused crash
=> Fix bug in uri_escape and uri_unescape.

http/server.lua, test/http.test.lua
Added callback for protocol upgrade implementations such as websockets.
=> protocol upgrade basic implementation

README.md
As branch 'tarantool-1.7' was deleted from repository url for 'Test' became broken.
This PR change url to master branch.
=> Fix url for 'Tests'

README.md
`self` usually means object variable, whose method is called.
Here we need a `request` object variable, so suitable name would be `request` or `req` and using name `self` is kinda confusing
=> Fix a variable name in "stash" and "cookies" code samples

http/router/matching.lua, test/integration/router_test.lua
Closes #105 
The bug was in incorrect ``specificity`` counting. 
``specificity`` is a how many symbols were not known (were hidden behind : and * patterns) in route's path. ``specificity`` was calculated as negative sum of symbols in regex groups, which were created from route's path.
```lua
local regex_groups_matched = {string.match(filter.path, r.match)}
```
But if match pattern has not any regex groups and string matches,  string.match returns all string.
Example:
```lua
tarantool> string.match('test/some', '^test/(.-)$')
---
- some
...
tarantool> string.match('test/some', '^test/some$')
---
- test/some
...
```
So if request's path is the same as route's path then string.match will return whole and this route will get the lowest priority.
So we need to explicitly add regex group which …
=> Fix routes overlapping by *any pattern in route's path

.travis.yml, README.md, http/router/init.lua, http/server/init.lua, test/integration/logging_test.lua
Closes #106 
This pr almost completely reproduces  #77, but added additional case handling:
If
```Lua
server.options.log_requests == false
server.options.log_errors == false
```
and
```Lua
route_options.log_requests == true
route_options.log_errors == true
```
then route would use ``log.info`` for requests logging and ``log.error`` for errors logging.
=> Return ability to use custom loggers and to set loggers for a specific route

.travis.yml
Because its repos are not available anymore
=> Don't build ubuntu cosmic package

http/router/fs.lua
In tarantool the standart built-in module for working with files is "fio".
So we should use it instead of "io".
Closes #112
=> Get rid of io module.

README.md, http/router/request.lua, http/router/response.lua, http/utils.lua, test/integration/request_test.lua, test/unit/setcookie_test.lua
`resp:setcookie` implicitly escaped cookie values. Added ability to set cookie without any escaping `resp:setcookie('name', 'value', {raw = true})`.
Also added escaping for cookie path, and changed escaping algorithm according to https://tools.ietf.org/html/rfc6265.
Closes #114
=> Added ability to set cookie without escaping.

http/lib.c, test/unit/lib_test.lua
=> Check ptr to string before use it

CHANGELOG.md
Release notes (draft): https://github.com/tarantool/http/releases/tag/untagged-1222b637904bbe78ea37
=> http v2 legacy release 2.1.1

rockspecs/http-1.0.1-1.rockspec, rockspecs/http-1.0.2-1.rockspec, rockspecs/http-1.1.1-1.rockspec, rockspecs/http-scm-1.rockspec
GitHub is going to disable unencrypted Git protocol, so `git://` URLs
will stop working soon (see [1]).
[1]: https://github.blog/2021-09-01-improving-git-protocol-security-github/
Part of https://github.com/tarantool/tarantool/issues/6587
=> rockspec: use git+https:// for git repository URL

CHANGELOG.md, CMakeLists.txt, README.md, cmake/FindTarantool.cmake, http/server.lua, test/helpers.lua, test/integration/http_server_requests_test.lua
Fixes https://github.com/tarantool/security/issues/8
Fixes #129 
Fixes #135 
Fixes a CMake warnings for passed package names
~~**PR depends on https://github.com/tarantool/http/pull/141**~~
NOTE: Issue https://github.com/tarantool/security/issues/8 must be closed manually after merging.
=> Disable option display_errors by default

Jenkinsfile
We don't use Jenkins as a CI for a long time, so config can be removed.
=> Remove Jenkinsfile

.github/workflows/test.yml, CMakeLists.txt, README.md, cmake/FindLuaCov.cmake, cmake/FindLuaCovCoveralls.cmake, deps.sh
Patch adds a support of code coverage for Lua source code and Coveralls
support, see [1].
1. https://coveralls.io/github/tarantool/http
=> Add code coverage and coveralls support

CHANGELOG.md, README.md, http/server.lua, test/unit/http_custom_socket_test.lua
In continuation [pull 158](https://github.com/tarantool/http/pull/158).
Please review and accept the changes. Admonitions have been taken into account.
Summary:
1. The `tcp_server` socket method call has been separated into a separate http `listen` method so that `listen` can be overridden and use a different socket.
2. `requirement('socket')` moved inside procedure as it is only referenced by the default implementation. If the procedure is overridden, then the call is not needed. Just too much.
On the other hand, placement on top makes sense for understanding what modules are needed or potentially needed. I don't know which is better. Ready to redo, of course.
3. Fixed syntax
4. Add info to README
5. Add unit test (for regress testing)
6. Add info to CHANGELOG
=> Added the ability to use a non-standard socket (for example, with support   for SSL)

test/unit/http_template_test.lua
```
$ ./.rocks/bin/luatest -c test/unit/http_template_test.lua 
.....
Ran 5 tests in 0.003 seconds, 5 successes, 0 failures
$ ./.rocks/bin/luacheck test/unit/http_template_test.lua 
Checking test/unit/http_template_test.lua         OK
Total: 0 warnings / 0 errors in 1 file
```
Fixes #44
=> Fix undeclared var error in test

CMakeLists.txt
luatest has an option --shuffle that allows to randomise the order of
tests. This can be useful to detect a test that passes just because it
happens to run after an unrelated test that leaves the system in a
favourable state. Patch enable tests shuffling with predefined random
seed generated by CMake [1]. Seed is useful for reproducing a problems
related to the specific test order.
1. https://cmake.org/cmake/help/latest/command/string.html#random
=> test: shuffle tests

http/server.lua, test/integration/http_server_requests_test.lua
By default URL-decode is not working for `+` sign in GET-arguments.
But since other web-servers perform such decoding, i believe it should be enabled.
=> uri_escape default configuration

.github/workflows/test.yml
Run tests for tarantool 2.10 release
=> ci: run tests with tarantool-2.10

README.md, http/server.lua
Add a ability to get the request path without decoding
Maybe it closes #56, but I'm not sure :)
=> Add the path_raw field to a request object

http-scm-1.rockspec
Added a missing version file entry to the `build.modules` list in the rockspec file. Now, when installing the module via rockspec, the http/version.lua file is copied to the installation location.
Closes #185
=> bug: fixed missing entry about version file

CHANGELOG.md, http/server.lua, test/integration/http_server_requests_test.lua
Do not treat ./ as invalid uri.
Fixes https://github.com/tarantool/http/issues/171.
```
$ .rocks/bin/luatest -v test/
...
=========================================================
Ran 56 tests in 0.648 seconds, 56 succeeded, 0 failed
```
=> Do not treat ./ as invalid uri

.github/workflows/test.yml, .luacheckrc, CHANGELOG.md, CMakeLists.txt, README.md, deps.sh, http-scm-1.rockspec, http/server.lua, roles/CMakeLists.txt, roles/httpd.lua, test/helpers.lua, test/integration/http_server_delete_test.lua, test/integration/httpd_role_test.lua, test/mocks/mock_role.lua, test/unit/httpd_role_test.lua
This patch adds `roles.http_server`. This role allows to configurate one or more HTTP servers. Those servers could be reused by several other roles.
Servers could be accessed by their names (from the config).
`get_server(name)` method returns a server by its name. If `nil` is passed, default server is returned. The server is  default, if it has `DEFAULT_SERVER_NAME` (`"default"`) as a name.
This patch also adds a `httpd:delete(name)` method to delete named routes.
Closes #196
=> roles: introduce role for http servers

CHANGELOG.md, http/version.lua
The release introduces a role for Tarantool 3.
- Fixed request crash with empty body and unexpected header Content-Type (#189).
- `roles.httpd` role to configure one or more HTTP servers (#196).
- `httpd:delete(name)` method to delete named routes (#197).
=> Release 1.6.0

http/server.lua
Check of ssl socket support occurs always, even if ssl is disabled.
After the patch support of ssl socket checks only if tls is enabled.
=> tls: fix error ssl socket support

CHANGELOG.md, README.md, http/server.lua, roles/httpd.lua, test/integration/httpd_role_test.lua, test/mocks/mock_role.lua, test/unit/httpd_role_test.lua
Since we support TLS in this module, we need to add it into roles too.
After the patch TLS params was added. It can be configurated like the following:
```yaml
server_name:
listen: "localhost:3013"
ssl_key_file: "path/to/key/file"
ssl_cert_file: "path/to/key/file"
ssl_ca_file: "path/to/key/file"
ssl_ciphers: "cipher1:cipher2"
ssl_password: "password"
ssl_password_file: "path/to/ssl/password"
```
Closes #199
=> roles: add tls support

http-scm-1.rockspec
Since TLS support was merged, it has been forgotten to add new `sslsocket.lua` file into rockspec. It's impossible to start installed http module without this file.
After the patch `sslsocket.lua` was added into rockspec file.
=> rockspec: add sslsocket

CHANGELOG.md, http/version.lua
The release introduces a TLS support.
- SSL support (#35).
- SSL support into roles (#199).
=> Release 1.7.0

.github/workflows/check_on_push.yaml, .github/workflows/packaging.yml, .github/workflows/publish.yaml, .github/workflows/test.yml
Ubuntu version 20.04 will soon be fully unsupported, so this patch updates it to 22.04.
Also old actions versions are updated and deprecated Tarantool versions are also changed.
https://github.com/actions/runner-images/issues/11101
Closes TNTP-1058
=> ci: update Ubuntu runners

CHANGELOG.md, roles/httpd.lua, test/helpers.lua, test/integration/httpd_role_test.lua, test/mocks/mock_role.lua, test/unit/httpd_role_test.lua
This patch-set fixes a several bugs related with config update.
Closes #209 
Closes #212
=> roles: fix bugs after config reload

CHANGELOG.md, README.md, roles/httpd.lua, test/integration/httpd_role_test.lua, test/unit/httpd_role_test.lua
Currently, HTTP requests are logged at the default level `log.info`, which can create noise (e.g. for metrics endpoints).
This change allows setting custom log levels (e.g. `log.verbose`) for incoming requests.
Example:
```yaml
roles_cfg:
roles.httpd:
default:
listen: 8081
log_requests: log.verbose
roles.metrics-export:
http:
- endpoints:
- path: /metrics
format: prometheus
```
Closes TNTP-3229
=> roles: add log_requests option
